name: Deploy Staging 🚀

on:
  push:
    branches:
      - test  # Ubah ini ke branch test

jobs:
  deploy_staging:
    name: Deploy to staging server
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Optional: Tambahkan step untuk auto merge ke main jika deployment sukses
      - name: Merge to main if successful
        if: success()
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute deployment command
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          script: |
            # Setup SSH for GitHub
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            echo "${{ secrets.GIT_SSH_KEY }}" > ~/.ssh/github_deploy_key
            chmod 600 ~/.ssh/github_deploy_key
            
            # Setup SSH config
            cat > ~/.ssh/config << EOF
            Host github.com
                HostName github.com
                User git
                IdentityFile ~/.ssh/github_deploy_key
                StrictHostKeyChecking no
            EOF
            chmod 600 ~/.ssh/config
            
            # Create directory if it doesn't exist
            sudo mkdir -p ${{ env.APP_STG_PATH }}
            sudo chown $USER:$USER ${{ env.APP_STG_PATH }}
            
            # Clone or update repository
            if [ -d "${{ vars.APP_STG_PATH }}/.git" ]; then
              echo "Updating existing repository..."
              cd ${{ vars.APP_STG_PATH }}
              git fetch origin
              git reset --hard origin/main
            else
              echo "Cloning new repository..."
              GIT_SSH_COMMAND='ssh -i ~/.ssh/github_deploy_key -o StrictHostKeyChecking=no' \
              git clone ${{ secrets.GIT_URL }} ${{ vars.APP_STG_PATH }}
              cd ${{ vars.APP_STG_PATH }}
            fi
            
            # Generate .env file
            cat > .env << EOL
            APP_STG_PORT=${{ secrets.APP_STG_PORT }}
            MINIO_STG_ENDPOINT=${{ secrets.MINIO_STG_ENDPOINT }}
            MINIO_STG_ACCESS_KEY=${{ secrets.MINIO_STG_ACCESS_KEY }}
            MINIO_STG_SECRET_KEY=${{ secrets.MINIO_STG_SECRET_KEY }}
            EOL
            
            # Docker deployment
            sudo docker compose up -d --build pacmusic-stg

            # Verify deployment
            echo "Waiting for container to start..."
            sleep 10
            
            if ! sudo docker compose ps | grep -q "pacmusic-stg.*Up"; then
              echo "Container status:"
              sudo docker compose ps
              echo "Container logs:"
              sudo docker compose logs pacmusic-stg
              exit 1
            fi

      - name: Verify Deployment
        run: |
          sleep 20
          curl -f ${{ secrets.STG_URL }}