name: Dev Testing 🔎

on:
  pull_request:
    branches: [ "main" ]

jobs:
    build_and_testing:
        name : build and test
        runs-on: ubuntu-latest
        environment: dev-testing
        steps:
          # Step 1: Checkout repository
          - name: Checkout repository
            uses: actions/checkout@v3

          # Step 2: Create .env file based on secrets
          - name: Create .env file
            run: |
              echo "MINIO_DEV_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT }}" >> .env
              echo "MINIO_DEV_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY }}" >> .env
              echo "MINIO_DEV_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY }}" >> .env
              echo "APP_IMAGE=your-image-name" >> .env
              echo "APP_TAG=latest" >> .env

          # Step 3: Start Docker Compose for dev environment
          - name: Start Docker Compose
            run: |
              sudo docker compose up --build --detach pacmusic-dev

          # Step 4: Test Hit Endpoint from the application
          - name: Hit Endpoint
            run: |
              sleep 10
              curl http://localhost:5000

